### ISSUE TITLE
Installation Tutorial

### ISSUE THREAD

**Issue by nmaster** [jumbojett/Wordpress-OpenID-Connect-Login#1]
A short step-by-step tutorial on how to install/configure/deploy the plug-in for a given (MITREid)  OIDC server would be of great help. README.md should be the perfect place.

**Comment by jumbojett** [comment]
@nmaster I agree. In the meantime, the following steps should work.
1. Clone and pull submodules `git clone --recursive https://github.com/jumbojett/Wordpress-OpenID-Connect-Login.git`
2. Copy the `Wordpress-OpenID-Connect-Login` directory to the wordpress plugins directory
3. Activate the plugin in wordpress
4. Visit the plugin's settings page in wordpress and populate appropriate values.

If these steps are successfully completed, then a link will appear at the bottom of the login form allowing additional authentication with the chosen provider.

**Comment by jumbojett** [comment]
Updated README
