### ISSUE TITLE
How would you recommend adding multiple IdP support?

### ISSUE THREAD

**Issue by dazzaji** [jumbojett/Wordpress-OpenID-Connect-Login#5]
Thanks for making this code available.  How would you suggest approaching further development of this Wordpress project to enable support for multiple Identity Providers?

Here is the context: I'm working on a couple of projects over the next month that seek to deploy OpenID Connect Relying Party (aka Client) applications with support for multiple Identity Providers.  Specifically, the projects will support Google's OpenID Connect flow and a deployment of the MITREid Connect implementation of OpenID Connect (https://github.com/mitreid-connect).  

The investment of effort to help update this code would, ideally, result with a relatively simple way for any number of additional identity providers to be added by site administrators.  Any suggestions on how best to approach this would be very welcome and naturally we'll make pull requests with any improvements we might be able to make in hopes of boosting the overall project.

**Comment by dazzaji** [comment]
Just notice your other branch... not sure whether you'd recommend following the direction you started there or not.  This seems to be the most up to date diffs: https://github.com/jumbojett/Wordpress-OpenID-Connect-Login/compare/multiple_providers

**Comment by jumbojett** [comment]
Hi @dazzaji, I'd recommend using the multiple providers branch. It currently works using OIDC auto-registration. I just made an attribute change a few minutes ago to align with the latest spec. Please submit pull requests.

**Comment by dazzaji** [comment]
Hi @jumbojett thanks you for the rapid response!  I'm spreading the word about using the multiple providers branch and your recent update now.  Me or somebody from the team (mostly in or around Kansas City) will let you know how it goes and hopefully have a nice pull request for you!
