### ISSUE TITLE
Issue with Retrieving User Information

### ISSUE THREAD

**Issue by PaladinMattt** [jumbojett/Wordpress-OpenID-Connect-Login#6]
Thanks for this plugin, it has helped a lot.  One issue is that as is, I am only getting null values when it attempts to access the userinfo_endpoint in OpenIDConnectClient.php5.  However, I downloaded OpenIDConnectClient.php from https://github.com/jumbojett/OpenID-Connect-PHP and swapped it out, and now it is working great. 
Thank you once again.

**Comment by jumbojett** [comment]
@PaladinMattt Thanks for capturing this. 👍 I'm hoping the developer community will contribute composer support so we can rid this repo of git submodules and allow fluent updates.
