### ISSUE TITLE
Reauth loop

### ISSUE THREAD

**Issue by binary-sort** [jumbojett/Wordpress-OpenID-Connect-Login#7]
Wordpress is creating a reauth loop.

Wordpress is behind a nginx load balancer, if this helps.

**Comment by jumbojett** [comment]
@binary-sort could provide more details? Have you been able to pinpoint the line in the code where this is taking place?

**Comment by binary-sort** [comment]
@jumbojett 
Hey, thanks for responding.
That was not the problem with plugin. It was due to some object cache plugin.

**Comment by binary-sort** [comment]
@jumbojett 
There is one more issue.
Plugin relies on email to check wp user, what is email in wp database and openid database are different but usernames are same?
