### ISSUE TITLE
Issue when using with IdentityServer (openId provider)

### ISSUE THREAD

**Issue by Nordes** [jumbojett/Wordpress-OpenID-Connect-Login#8]
When trying to connect the wordpress with an OpenId provider like IdentityServer i get the following errors and I tried to find where it was coming from but didn't succeed yet (at the time of this writing)

```
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/Wordpress-OpenID-Connect-Login/lib/auth/OpenIDConnectClient.php5 on line 374

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/Wordpress-OpenID-Connect-Login/lib/auth/OpenIDConnectClient.php5 on line 360

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/Wordpress-OpenID-Connect-Login/lib/auth/OpenIDConnectClient.php5 on line 374

Your email address has not been verified with your provider.
```

I login successfully, but however I am not able to proceed further ;).

**Comment by jumbojett** [comment]
https://github.com/jumbojett/Wordpress-OpenID-Connect-Login/blob/e4439536c9f313a24106adc2701e419267c63cd9/plugin.php#L172

This is an OIDC check to verify when a user has confirmed their email. You can comment out this line or change it to suite your needs.
